function [pdbTransformation optimizedTrm] = getOptimizedTransformation(...
    pdbBegin, pdbEnd, conformationsCount,...   
    bidirectionAngleThreshold, modelNumber, trmAnglesCountToOptimize,...
    trmCostFunction, trmCostFunctionAdditionalParameters, ...
    maxIter, tolx, ...
    outputPdbPath)
%GETOPTIMIZEDTRANSFORMATION Summary of this function goes here
%   Detailed explanation goes here
%
% By Sergey Knyazev, 2014.
% sergey.n.knyazev@gmail.com

initTrm = trmcreate(pdbBegin, pdbEnd,conformationsCount);
initTrms = trmGenerateInitialModels(initTrm, [],...
    bidirectionAngleThreshold);
optimizedTrm = trmsOptimize(initTrms, modelNumber,...
    trmAnglesCountToOptimize, trmCostFunction,...
    trmCostFunctionAdditionalParameters, 'interior-point', maxIter, tolx);

for i=1:length(optimizedTrm)
    pdbTransformation(i) = trm2pdb(optimizedTrm(i), pdbBegin);
    pdbwrite([outputPdbPath '/result' int2str(i) '.pdb'],...
        pdbTransformation(i));
end

