function [optimizedLoopsTrms loopsAnglesIntervals ] ...
    = pdbExtractAndOptimizeLoops(...
    beginTransformationPdb, endTransformationPdb, ...
    initIntermediateConformationsCount, ...
    loopMinAngleDiff, loopVicinity, ...
    loopBorderAtomMass, ...
    minBidirectionAngleValue, ...
    minAngleValueChangeToBeOptimized, trmCostFunction, ...
    trmCostFunctionAdditionalParameters, algorithm, MaxIter, tolx, ...
    outputPdbPath)
%PDBEXTRACTANDOPTIMIZELOOPS Function creates protein transformation model
%   from begin and end pdb structures, extracts loops regions and 
%   optimizes them.
%   [optimizedLoopsTrms loopsAnglesIntervals ] ...
%   = pdbExtractAndOptimizeLoops(...
%   beginTransformationPdb, endTransformationPdb, ...
%   initIntermediateConformationsCount, ...
%   loopMinAngleDiff, maxLoopsAnglesCount, loopVicinity, ...
%   loopBorderAtomMass, ...
%   minBidirectionAngleValue, ...
%   minAngleValueChangeToBeOptimized, trmCostFunction, ...
%   trmCostFunctionAdditionalParameters, algorithm, MaxIter, tolx, ...
%   outputPdbPath)
%   Output:
%   optimizedLoopsTrms - optimized transformations of protein parts
%   loopsAnglesIntervals - n*2 matrix, where n - number of loops in
%       protein, loopsAnglesIntervals(i,1) - first torsion angle of loop
%       in protein transformation model, loopsAnglesIntervals(i,2) - 
%       last torsion angle of loop in protein transformation model.
%   Input:
%   beginTransformationPdb - begin protein model. Is used as first
%       conformation in protein transformation model.
%   endTransformationPdb - end protein model.  Is used as last
%       conformation in protein transformation model.
%   initIntermediateConformationsCount - count of intermediate
%       transformations in protein transformation model.
%   loopMinAngleDiff - angle value change between the same torsion angle
%       in first and last conformations in protein transformation model.
%       This value is used to determain angle as loop. Amino acid recidue
%       with loop angle is considered as part of loop region.
%   loopVicinity - count of amino acid residue around amino acid residue
%       with loop angle. These amino acid recidue are considered as part 
%       of loop region.
%   loopBorderAtomMass - Mass of first and last three atoms in every loop
%       region.
%   minBidirectionAngleValue - see trmGenerateInitialModels function for
%       details.
%   minAngleValueChangeToBeOptimized - angle value change between the same
%       torsion angle in first and last conformations in protein
%       transformation model. This value is used to determain angles to be
%       optimized.
%   trmCostFunction - Transformation model cost function.
%   trmCostFunctionAdditionalParameters - trmCostFunction additional
%       parameters.
%   algorithm, MaxIter, tolx - See fmincon for details.
%   outputPdbPath - folder for storing pdb files with loops
%       transformations.
%
%   Example:
%       [optimizedLoopsTrms20 loopsAnglesIntervals20] = ...
%           pdbExtractAndOptimizeLoops(pdb2W8N, pdb2W8O, 6, 2.1, 2, ...
%           1e7, 2.49, [], @trmcostlp, [2], 'interior-point', 1000, ...
%           10e-7, [korea_20_02_2013_path 'loops20']);
%
% Protein Transformation Toolbox for MATLAB
%
% By Sergey Knyazev, 2012.
% sergey.n.knyazev@gmail.com

initTrm = trmcreate(beginTransformationPdb,  endTransformationPdb, ...
    initIntermediateConformationsCount);
[loopsInitTrms, loopsAnglesIntervals, ~, ~] = ...
    trmGetLoops(initTrm, loopMinAngleDiff, [], loopVicinity, ...
    loopBorderAtomMass);
loopsInitialModels = trmGenerateLoopsInitialModels(loopsInitTrms, ...
    minBidirectionAngleValue);
optimizedLoopsTrms = trmOptimizeLoops(loopsInitialModels, ...
    minAngleValueChangeToBeOptimized, trmCostFunction, ...
    trmCostFunctionAdditionalParameters, algorithm, MaxIter, tolx);
if ~isempty(outputPdbPath)
    optimizedLoopsPdbs = trmsLoops2pdbs(...
        beginTransformationPdb,optimizedLoopsTrms,loopsAnglesIntervals);
    pdbWriteLoops(optimizedLoopsPdbs, loopsAnglesIntervals, outputPdbPath);
end
end

